#!/usr/bin/env bash
#
# A script to generate stable checksums from multiple
# build.gradle files.
#
# Usage: checksums FILE

RESULT=$1

if [ -f "$RESULT" ]; then
  rm -f "$RESULT"
fi
touch "$RESULT"

find . -name build.gradle -exec sh -c "openssl md5 '{}' | awk '{print \$2}' >> '$RESULT'" \;

sort "$RESULT" -o "$RESULT"
